import pandas as pd
from pathlib import Path

cwd = Path.cwd()
print(f'Current path: {cwd}')

file_path = cwd / 'Programs'/ 'Wykresy - temperatura'
temperatura_df = pd.read_csv( file_path / 'temperatura.csv')

print('Data frame:')
print(temperatura_df)
print()

# print('Data frame - 1:')
# print(temperatura_df.sample(1))
# print()

# print('Data frame - 2:')
# print(temperatura_df[temperatura_df.sample(1)])
# print()

# print('Data frame - 3:')
# print(temperatura_df['Godzina'])
# print()

print("czy duplikaty?")
print(temperatura_df.duplicated())
print()
print("pokaż te duplikaty")
print(temperatura_df[temperatura_df.duplicated()])
print()
print("mean")
print(temperatura_df.mean())
print()
print("cały df:")
print(temperatura_df)
print()
print("Porzucam duplikaty")
temperatura_df = temperatura_df.drop_duplicates(subset='Temperatura')
print("duplikaty porzucone")
print("data frame bez duplikatów:")
print(temperatura_df)
print()
print("Tylko pierwsza kolumna")
print(temperatura_df['Godzina'])
print()
print("Tylko druga kolumna")
print(temperatura_df['Temperatura'])
print()
print("Średnia z kolumny Godzina")
print(temperatura_df['Godzina'].mean())
print()
print("Średnia z kolumny Temperatura")
print(temperatura_df['Temperatura'].mean())
print()
print("Mediana z kolumny Godzina")
print(temperatura_df.Godzina.median())
print()
print("Mediana z kolumny Temperatura")
print(temperatura_df.Temperatura.median())
print()