numbers_given = []
print('Type 5 numbers')
first_no = input('First:')
numbers_given.append(first_no)
second_no = input('Second:')
numbers_given.append(second_no)
third_no = input('Third:')
numbers_given.append(third_no)
fourth_no = input('Fourth:')
numbers_given.append(fourth_no)
fifth_no = input('Fifth:')
numbers_given.append(fifth_no)
numbers_given.sort()
print('Sorted list:', numbers_given)